import { readFileSync } from 'node:fs'
import { expect, test } from 'vitest'

const companies = readFileSync('src/components/CompaniesPage.tsx','utf8')
const profile = readFileSync('src/components/CompanyProfilePage.tsx','utf8')
const css = readFileSync('src/styles/known-firms.css','utf8')
const app = readFileSync('src/App.tsx','utf8')
const account = readFileSync('src/components/UserAccountPage.tsx','utf8')
const admin = readFileSync('src/components/AdminCompaniesPage.tsx','utf8')
const adminDetail = readFileSync('src/components/AdminCompanyProfilePage.tsx','utf8')

test('public Known Firms stays free of private company administration', () => {
  expect(companies).not.toContain('companyAdmin')
  expect(companies).not.toContain('CompanyAdmin')
  expect(companies).not.toContain('CRM relationship status')
  expect(companies).not.toContain('Admin database')
  expect(companies).not.toContain('admin-filters')
  expect(companies).not.toContain('admin-company-table')
  expect(companies).toContain('Known companies & firms')
  expect(companies).toContain('Known firm search')
  expect(companies).toContain('Known firm role')
  expect(companies).toContain('Known firm relationship')
  expect(companies).toContain('Known firm activity')
  expect(companies).toContain('Known firm identity confidence')

  expect(profile).not.toContain('CompanyAdminPanel')
  expect(profile).not.toContain('CompanyFamilyPanel')
  expect(profile).not.toContain('CompanyAuditHistory')
  expect(css).not.toContain('.firm-master-filters.admin-filters')
  expect(css).not.toContain('.known-firms-master-table.admin-company-table')
})

test('private company administration has dedicated routes and dashboard surfaces', () => {
  expect(app).toContain("'admin-companies'")
  expect(app).toContain("'admin-company'")
  expect(app).toContain('<AdminCompaniesPage />')
  expect(app).toContain('<AdminCompanyProfilePage companyId={selectedAdminCompanyId} />')
  expect(account).toContain('href="#/admin-companies"')
  expect(admin).toContain('Company command center')
  expect(admin).toContain('Parent company summary')
  expect(admin).toContain('Enrichment coverage')
  expect(admin).toContain('CRM pipeline')
  expect(admin).toContain('Company family directory')
  expect(admin).toContain('Research queue & follow-up operations')
  expect(adminDetail).toContain('Master company summary')
  expect(adminDetail).toContain('Family identities')
  expect(adminDetail).toContain('CompanyAdminPanel')
  expect(adminDetail).toContain('CompanyFamilyPanel')
  expect(adminDetail).toContain('CompanyAuditHistory')
})
