import { expect, test } from './fixtures'
import { expectContained } from './iphone.helpers'

test('Monitor uses occurrence dates, readable evidence and contained desktop/mobile rows', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000)
  await page.evaluate(() => { location.hash = '#/monitor' })
  await expect(page.getByRole('heading', { name: 'Monitor workspace', exact: true })).toBeVisible()
  const panel = page.getByRole('region', { name: 'TowerSignal changes' })
  await expect(panel.getByTestId('monitor-event-count')).toBeVisible()
  await panel.getByRole('tab', { name: /^Violations/ }).click()
  await expect(panel.locator('.change-reference-row').first()).toBeVisible()
  const dates = await panel.locator('.monitor-source-date time').evaluateAll(elements => elements.map(el => el.getAttribute('datetime')))
  const known = dates.filter((date): date is string => Boolean(date))
  expect(known.length).toBeGreaterThan(0)
  expect(known).toEqual([...known].sort().reverse())
  await expectContained(page)
  await page.evaluate(() => window.scrollTo(0, 0))
  await testInfo.attach('monitor-source-dates', { body: await page.screenshot({ fullPage: true, scale: 'css', animations: 'disabled' }), contentType: 'image/png' })

  await panel.getByLabel('Event date range').selectOption('custom')
  await panel.getByLabel('From', { exact: true }).fill('2026-07-14')
  await panel.getByLabel('To', { exact: true }).fill('2026-07-14')
  await panel.getByLabel('Borough', { exact: true }).selectOption('Manhattan')
  const madison = panel.locator('.change-reference-row').filter({ hasText: '1414 MADISON AVE' }).filter({ hasText: 'AH8A' }).first()
  await expect(madison).toBeVisible()
  await expect(madison.locator('time')).toHaveAttribute('datetime', '2026-07-14')
  await expect(madison.locator('time')).toHaveText('Jul 14, 2026')
  await expect(madison.getByText('Inspection date', { exact: true })).toBeVisible()
  await expect(madison.getByText('No Maintenance Program or Plan', { exact: true })).toBeVisible()
  await expect(madison.locator('.monitor-source-name')).toHaveText('NYC Health inspections')
  const firstSeen = madison.getByText(/^First seen by TowerSignal/)
  await expect(firstSeen).toBeHidden()
  await madison.locator('.monitor-row-provenance summary').click()
  await expect(firstSeen).toBeVisible()
  await expect(page).toHaveURL(/#\/monitor$/)
  await madison.locator('.monitor-row-provenance summary').click()
  await expect(firstSeen).toBeHidden()
  await expectContained(page)
  await page.evaluate(() => window.scrollTo(0, 0))
  await testInfo.attach('monitor-madison-july-14', { body: await page.screenshot({ fullPage: true, scale: 'css', animations: 'disabled' }), contentType: 'image/png' })
  await expect(madison.getByRole('link', { name: 'Open account', exact: true })).toHaveAttribute('href', '#/account/2000015925')
  await panel.getByLabel('From', { exact: true }).fill('2026-09-15')
  await panel.getByLabel('To', { exact: true }).fill('2026-09-15')
  await expect(panel.getByText('1414 MADISON AVE', { exact: true })).toHaveCount(0)
})
