import { expect, test } from './fixtures'
import { expectContained, expectAccountDetailHydrated } from './iphone.helpers'

test('Existing Home building links reach reviewed account scoring and source-dated Monitor', async ({ page }, testInfo) => {
  test.setTimeout(150_000)
  const panel = page.getByRole('region', { name: 'Legionnaires official intelligence' })
  await expect(panel).toBeVisible()
  await panel.getByLabel('Search official intelligence').fill('orders cooling towers')
  const article = panel.locator('tr').filter({ has: page.locator('a.li-headline[href*="orders-cooling-towers"]') })
  await expect(article.locator('time')).toHaveText('Sep 13, 2026')
  await expect(article.locator('.li-match-button')).toContainText('10 buildings')
  await article.locator('.li-match-button').click()
  await panel.getByRole('link', { name: 'Open tower account 2000003324', exact: true }).click()
  await expectAccountDetailHydrated(page)
  await expect(page.getByLabel('Official building health evidence')).toBeVisible()
  await expect(page.getByLabel('Official building health evidence')).toContainText('Order date Sep 12, 2026')
  const score = page.getByLabel('Priority score explanation')
  await expect(score).toBeVisible()
  const releasedScoring = await page.evaluate(async () => {
    const response = await fetch(new URL('data/details/20/2000003324.json', location.href))
    if (!response.ok) throw new Error(`Released account HTTP ${response.status}`)
    return (await response.json()).scoring
  })
  expect(releasedScoring.priority_model_version).toBeTruthy()
  await expect(score).toContainText(`Research priority model ${releasedScoring.priority_model_version}`)
  await expect(score).toContainText('Building-level match')
  await expectContained(page)
  await page.evaluate(() => scrollTo(0, 0))
  await testInfo.attach('reviewed-bronx-account', { body: await page.screenshot({ scale: 'css', fullPage: true }), contentType: 'image/png' })

  await page.evaluate(() => { location.hash = '#/monitor' })
  await expect(page.getByRole('heading', { name: 'Monitor workspace', exact: true })).toBeVisible()
  const monitor = page.getByRole('region', { name: 'TowerSignal changes' })
  await monitor.getByRole('tab', { name: /^Violations/ }).click()
  await expect(monitor.locator('.change-reference-row').first()).toBeVisible()
  const dates = await monitor.locator('.monitor-source-date time').evaluateAll(nodes => nodes.map(n => n.getAttribute('datetime')).filter(Boolean))
  expect(dates.length).toBeGreaterThan(0)
  expect(dates).toEqual([...dates].sort().reverse())
  await monitor.getByLabel('Event date range').selectOption('custom')
  await monitor.getByLabel('From', { exact: true }).fill('2026-07-14')
  await monitor.getByLabel('To', { exact: true }).fill('2026-07-14')
  await monitor.getByLabel(/^Borough/).selectOption('Manhattan')
  const madison = monitor.locator('.change-reference-row').filter({ hasText: '1414 MADISON AVE' }).filter({ hasText: 'AH8A' }).first()
  await expect(madison).toBeVisible()
  await expect(madison.locator('time')).toHaveAttribute('datetime', '2026-07-14')
  await expect(madison).toContainText('No Maintenance Program or Plan')
  await expect(madison).not.toContainText('{"')
  const firstSeen = madison.getByText(/^First seen by TowerSignal/)
  await expect(firstSeen).toBeHidden()
  await madison.locator('.monitor-row-provenance summary').click()
  await expect(firstSeen).toBeVisible()
  await expect(page).toHaveURL(/#\/monitor$/)
  await madison.locator('.monitor-row-provenance summary').click()
  await expectContained(page)
  await page.evaluate(() => scrollTo(0, 0))
  await testInfo.attach('monitor-madison-july-14', { body: await page.screenshot({ scale: 'css', fullPage: true }), contentType: 'image/png' })
  await expect(madison.getByRole('link', { name: 'Open account', exact: true })).toHaveAttribute('href', '#/account/2000015925')
  await monitor.getByLabel('From', { exact: true }).fill('2026-09-15')
  await monitor.getByLabel('To', { exact: true }).fill('2026-09-15')
  await expect(monitor.getByText('1414 MADISON AVE', { exact: true })).toHaveCount(0)

  // A newly scored project-only account must not still claim there is no signal.
  await page.evaluate(() => { location.hash = '#/account/2000000164' })
  await expectAccountDetailHydrated(page)
  const projectSignal = page.locator('.signal-card').filter({ hasText: 'Recent cooling-tower project' })
  await expect(projectSignal).toBeVisible()
  await expect(projectSignal).toContainText('Jul 2, 2026')
  await expect(projectSignal).toContainText('M01279376-S2')
  await expect(page.getByLabel('Priority score explanation')).toContainText('15 / 100')
  await expect(page.getByLabel('Priority score explanation')).toContainText('M01279376-S2')
  await expectContained(page)
  await testInfo.attach('project-only-priority-account', { body: await page.screenshot({ scale: 'css', fullPage: true }), contentType: 'image/png' })

})
