import {test, expect, type Page, type Locator} from '@playwright/test'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
const OUT='promo-distinct-views';mkdirSync(OUT+'/screens',{recursive:true});mkdirSync(OUT+'/states',{recursive:true});
test.use({viewport:{width:1440,height:1100},deviceScaleFactor:2,trace:'off'});
async function go(page:Page,hash:string){await page.goto('./'+hash,{waitUntil:'domcontentloaded',timeout:90000});await expect(page.locator('.app-shell')).toBeVisible({timeout:90000});await expect(page.locator('.loading-page')).toHaveCount(0,{timeout:90000});await page.waitForTimeout(1800);await page.evaluate(()=>document.fonts.ready)}
async function snap(page:Page,name:string,selector?:string|Locator){const target=typeof selector==='string'?page.locator(selector).first():selector;if(target){await expect(target).toBeVisible();await target.evaluate(e=>window.scrollTo(0,Math.max(0,e.getBoundingClientRect().top+window.scrollY-110)));await page.waitForTimeout(900);await target.screenshot({path:OUT+'/screens/'+name+'.png',animations:'disabled',timeout:60000})}else{await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:OUT+'/screens/'+name+'.png',fullPage:true,animations:'disabled',timeout:60000})}const j=await page.evaluate(()=>({url:location.href,title:document.title,text:document.body.innerText,scripts:[...document.querySelectorAll('script[src]')].map(e=>(e as HTMLScriptElement).src)}));writeFileSync(OUT+'/states/'+name+'.json',JSON.stringify({...j,captured_at:new Date().toISOString(),viewport:page.viewportSize(),device_scale_factor:2,method:'Actual hosted screenshot; no content, CSS or data substitution',sha256:createHash('sha256').update(readFileSync(OUT+'/screens/'+name+'.png')).digest('hex'),selected_text:target?await target.innerText():null},null,2))}
async function mode(page:Page,id:string,name:string){await go(page,'#/account/'+id);await page.getByRole('button',{name:new RegExp('^'+name+'\\s')}).first().click();await page.waitForTimeout(1000)}
test('CUNY sales briefing and observed roles',async({page})=>{test.setTimeout(180000);await mode(page,'2000012577','Sales');await snap(page,'cuny-sales-full');await snap(page,'cuny-sales-brief','.sales-precall-pack');await snap(page,'cuny-sales-metrics','.sales-pack-metrics');await snap(page,'cuny-before-call','.sales-pack-panel');await snap(page,'cuny-call-objective','.sales-pack-objective');const firms=page.locator('.sales-known-firms');if(await firms.count()){if(await firms.getAttribute('open')===null)await firms.locator('summary').click();await snap(page,'cuny-observed-firms',firms)}})
test('Central Park South roof and domestic water',async({page})=>{test.setTimeout(180000);await mode(page,'2000000855','Field');await snap(page,'central-park-field-full');await snap(page,'central-park-field-pack','.technician-field-pack');await snap(page,'central-park-roof','.planimetric-section');await snap(page,'central-park-roof-map','.planimetric-map-shell');await snap(page,'central-park-roof-summary','.planimetric-summary');await snap(page,'central-park-roof-legend','.roof-map-legend');await snap(page,'central-park-domestic','.domestic-water-section')})
test('East 39 Street history and sales',async({page})=>{test.setTimeout(180000);await mode(page,'2000015564','History');await snap(page,'east39-history-full');await snap(page,'east39-timeline','.account-unified-timeline');await mode(page,'2000015564','Sales');await snap(page,'east39-sales-brief','.sales-precall-pack');await snap(page,'east39-sales-metrics','.sales-pack-metrics')})
test('Central Park South property evidence',async({page})=>{test.setTimeout(120000);await mode(page,'2000000855','Evidence');await snap(page,'central-park-evidence-full')})
test('Metro Group relationship and procurement details',async({page})=>{test.setTimeout(180000);await go(page,'#/company/observed-company-9a049993a3ba62961d8f');await snap(page,'metro-full');const row=page.locator('.firm-prospect-sites-table tbody tr').filter({hasText:/515 east 72nd/i}).first();if(await row.count()){await row.click();await page.waitForTimeout(2000);await snap(page,'metro-selected-map','.firm-site-map-grid')}await snap(page,'metro-commercial',page.locator('.company-evidence-card').filter({hasText:'Commercial footprint'}).first());await snap(page,'metro-procurement',page.locator('.firm-evidence-card').filter({hasText:'Public procurement observations'}).first())})
test('Water samples source health and Home details',async({page})=>{test.setTimeout(180000);await go(page,'#/source-health');await snap(page,'source-health-full');await go(page,'#/water-quality');await page.getByRole('button',{name:'NYC Distribution',exact:true}).click();await page.getByRole('button',{name:'Samples',exact:true}).waitFor({state:'visible',timeout:60000});await page.getByRole('button',{name:'Samples',exact:true}).click();await page.waitForTimeout(2000);await snap(page,'water-samples-full');await go(page,'#/home');await page.getByRole('button',{name:'Linked buildings',exact:true}).click();await snap(page,'home-linked-full')})
test('Manhattan prioritized map',async({page})=>{test.setTimeout(120000);await go(page,'#/map?borough=Manhattan&minScore=70');await page.waitForTimeout(4000);await snap(page,'manhattan-map-full');await snap(page,'manhattan-map','.map-shell');for(let i=0;i<2;i++){await page.locator('.map-shell .leaflet-control-zoom-in').click();await page.waitForTimeout(1500)}await snap(page,'manhattan-map-zoom','.map-shell')})
