import {test,expect,type Page,type Locator} from '@playwright/test'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
const OUT='promo-fresh-market';mkdirSync(OUT+'/screens',{recursive:true});mkdirSync(OUT+'/states',{recursive:true});test.use({viewport:{width:1440,height:1100},deviceScaleFactor:2,trace:'off'});
async function go(page:Page,hash:string){await page.goto('./'+hash,{waitUntil:'domcontentloaded',timeout:90000});await page.waitForTimeout(2000);await expect(page.locator('.loading-page')).toHaveCount(0,{timeout:90000});await expect(page.getByRole('heading',{name:'Sign in to TowerSignal',exact:true})).toHaveCount(0);await page.evaluate(()=>document.fonts.ready)}
async function snap(page:Page,name:string,selector?:string|Locator){const l=typeof selector==='string'?page.locator(selector).first():selector;if(l){await expect(l).toBeVisible();await l.evaluate(e=>scrollTo(0,Math.max(0,e.getBoundingClientRect().top+scrollY-110)));await page.waitForTimeout(800);await l.screenshot({path:OUT+'/screens/'+name+'.png',animations:'disabled',timeout:60000})}else{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:OUT+'/screens/'+name+'.png',fullPage:true,animations:'disabled',timeout:60000})}const j=await page.evaluate(()=>({url:location.href,title:document.title,text:document.body.innerText,scripts:[...document.querySelectorAll('script[src]')].map(e=>(e as HTMLScriptElement).src)}));writeFileSync(OUT+'/states/'+name+'.json',JSON.stringify({...j,captured_at:new Date().toISOString(),viewport:page.viewportSize(),device_scale_factor:2,method:'Actual hosted desktop browser pixels; native interactions; no UI or public data substitution',demonstration:name.startsWith('workflow-demo'),sha256:createHash('sha256').update(readFileSync(OUT+'/screens/'+name+'.png')).digest('hex'),selected_text:l?await l.innerText():null},null,2))}
test('latest market views',async({page})=>{test.setTimeout(240000);for(const [hash,name] of [['#/prospect','prospect'],['#/monitor','monitor'],['#/opportunities','opportunities'],['#/nys','nys-market'],['#/nys-changes','nys-changes'],['#/companies','firms'],['#/portfolios','portfolios'],['#/source-health','source-health']]){await go(page,hash);await snap(page,name)}await go(page,'#/prospect?borough=Manhattan&minScore=70');await snap(page,'prospect-manhattan')})
test('current Home official intelligence tabs',async({page})=>{test.setTimeout(180000);await go(page,'#/home');await expect(page.getByRole('button',{name:'Linked buildings',exact:true})).toBeVisible({timeout:60000});await snap(page,'home');for(const name of ['Linked buildings','Reference library']){await page.getByRole('button',{name,exact:true}).click();await page.waitForTimeout(1200);await snap(page,'home-'+name.toLowerCase().replace(' ','-'))}})
test('native demonstration watchlist on real public accounts',async({page})=>{test.setTimeout(240000);for(const id of ['2000012577','2000000855','2000015564']){await go(page,'#/account/'+id);const sec=page.locator('.workflow-account-section').first();await sec.locator('select').first().selectOption('monitor');await sec.getByRole('checkbox').first().check();await sec.getByRole('button',{name:'Save workflow state',exact:true}).click();await page.waitForTimeout(1800)}await go(page,'#/workflow');await expect(page.locator('.workflow-command-table tbody tr')).toHaveCount(3,{timeout:30000});await page.locator('.workflow-command-table tbody tr').filter({hasText:'1813 Oriental'}).first().click();await page.waitForTimeout(1600);await snap(page,'workflow-demo-full');await snap(page,'workflow-demo-map','.workflow-command-map');await snap(page,'workflow-demo-inspector','.workflow-account-inspector');await snap(page,'workflow-demo-table','.workflow-command-table-card');await snap(page,'workflow-demo-quickviews','.workflow-command-strip');await page.getByRole('tab',{name:/^Changes/}).click();await snap(page,'workflow-demo-changes','.workflow-command-table-card');writeFileSync(OUT+'/DEMONSTRATION.txt','The normal hosted E2E setup created an isolated test profile. Three existing public properties were added through native UI as a demonstration watchlist, each with status Monitor and no sales notes or next-action dates. These are not customer results or the user private workflow. No public source data or production UI code was changed. Test-profile demonstration records are retained only in that isolated profile.\n')})
