import { useEffect, useState, type ReactNode } from 'react'
import { loadSystemDetail } from '../data/api'
import { formatDate, formatTimestamp } from '../domain/labels'
import { leadSummary } from '../utils/export'
import type { Metadata, SystemDetail, SystemSummary } from '../types/data'
import type { ChangeEvent } from '../types/history'
import { StatusBadge } from './StatusBadge'
import { AcrisActivitySection } from './AcrisActivitySection'
import { PlanimetricTowerSection } from './PlanimetricTowerSection'
import { TechnicianFieldPack } from './TechnicianFieldPack'
import { BuildingWaterSignalsSection } from './BuildingWaterSignalsSection'
import { LeadServiceLineSection } from './LeadServiceLineSection'

const money = (value: number | null) => value == null ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value)
const number = (value: number | null) => value == null ? '—' : new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(value)
const historyLabel = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/^./, letter => letter.toUpperCase())
const compactHistoryValue = (value: unknown) => value == null ? '—' : typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' ? String(value) : JSON.stringify(value)
const daysAsYears = (value: number | null) => value == null ? '—' : `${(value / 365.2425).toFixed(1)} years`
const dobRelevanceLabel = (value: string) => value === 'COOLING_TOWER_EXPLICIT' ? 'Cooling tower mention' : value === 'MECHANICAL_OR_BOILER' ? 'Mechanical / boiler' : 'Property project'

export function DetailPanel({ row, metadata, historyEvents, historyStartedAt, workflowSection, onClose }: { row: SystemSummary | null; metadata: Metadata; historyEvents: ChangeEvent[]; historyStartedAt: string; workflowSection?: ReactNode; onClose: () => void }) {
  const [detail, setDetail] = useState<SystemDetail | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)
  useEffect(() => {
    setDetail(null); setError(null); setCopied(false)
    if (!row) return
    loadSystemDetail(row.system_id).then(setDetail).catch(err => setError(err instanceof Error ? err.message : 'Unable to load system details'))
  }, [row])
  if (!row) return null
  const copy = async () => {
    if (!detail) return
    await navigator.clipboard.writeText(leadSummary(row, metadata, detail))
    setCopied(true)
  }
  return <aside className="detail-panel" aria-label="Selected cooling tower detail">
    <div className="detail-header"><div><span className="eyebrow">Selected system</span><h2>{row.address ?? row.system_id}</h2><p>{row.borough} {row.zip} · System <span className="mono">{row.system_id}</span></p></div><button className="icon-button" onClick={onClose} aria-label="Close details">×</button></div>
    <div className="detail-actions"><button onClick={copy} disabled={!detail}>{copied ? 'Copied' : 'Copy lead brief'}</button><span className="score large">{row.priority_score}</span><span>Priority score</span></div>
    {workflowSection}
    {error && <div className="error-state">{error}</div>}
    {!detail && !error && <div className="loading-state">Loading source-backed details…</div>}
    {detail && <>
      <TechnicianFieldPack row={row} detail={detail} />
      <section><h3>Identity</h3><dl className="identity-grid"><div><dt>BIN</dt><dd>{detail.identity.bin ?? '—'}</dd></div><div><dt>BBL</dt><dd>{detail.identity.bbl ?? '—'}</dd></div><div><dt>Active equipment</dt><dd>{detail.identity.active_equipment}</dd></div><div><dt>Coordinates</dt><dd>{detail.identity.coordinate_status === 'VALID' && detail.identity.latitude != null && detail.identity.longitude != null ? `${detail.identity.latitude.toFixed(4)}, ${detail.identity.longitude.toFixed(4)}` : detail.identity.coordinate_status === 'INVALID_SOURCE' ? `Unusable source coordinates (${detail.identity.source_latitude_raw ?? 'blank'}, ${detail.identity.source_longitude_raw ?? 'blank'})` : 'Not published'}</dd></div></dl></section>
      <PlanimetricTowerSection detail={detail} />
      <BuildingWaterSignalsSection detail={detail} />
      <LeadServiceLineSection detail={detail} />
      <section><h3>Building context</h3>{!detail.building_context ? <div className="empty-inline">No exact BBL match was returned from NYC DCP PLUTO for this system.</div> : <><dl className="identity-grid"><div><dt>PLUTO owner</dt><dd>{detail.building_context.owner_name ?? '—'}</dd></div><div><dt>Land use</dt><dd>{detail.building_context.land_use ?? '—'}</dd></div><div><dt>Building class</dt><dd>{detail.building_context.building_class ?? '—'}</dd></div><div><dt>Year built</dt><dd>{detail.building_context.year_built || '—'}</dd></div><div><dt>Building area</dt><dd>{number(detail.building_context.building_area_sqft)} sq ft</dd></div><div><dt>Lot area</dt><dd>{number(detail.building_context.lot_area_sqft)} sq ft</dd></div><div><dt>Floors</dt><dd>{number(detail.building_context.floors)}</dd></div><div><dt>Total units</dt><dd>{detail.building_context.total_units ?? '—'}</dd></div></dl><p className="microcopy">Context from NYC Department of City Planning PLUTO, joined by exact BBL. These property attributes do not affect TowerSignal's priority score or cooling-tower compliance signals.</p></>}</section>
      <section><h3>HPD registered contacts</h3>{!detail.hpd_registration ? <div className="empty-inline">No exact BBL match was found in NYC HPD Multiple Dwelling Registrations. HPD coverage applies to qualifying residential properties, so no match does not mean no owner or manager exists.</div> : <><p>Registration {detail.hpd_registration.registration_id ?? '—'}{detail.hpd_registration.last_registration_date ? ` · processed ${formatDate(detail.hpd_registration.last_registration_date)}` : ''}</p>{detail.hpd_registration.contacts.length === 0 ? <div className="empty-inline">An HPD registration matched this BBL, but no contact rows were returned for that registration.</div> : <div className="signal-list">{detail.hpd_registration.contacts.map((contact,index) => <article className="signal-card" key={`${contact.registration_contact_id ?? 'contact'}-${index}`}><div className="signal-card-head"><strong>{contact.type ?? 'HPD contact'}</strong></div><p>{contact.corporation_name ?? contact.person_name ?? contact.description ?? 'Name not published'}</p><dl className="identity-grid"><div><dt>Contact person</dt><dd>{contact.person_name ?? '—'}</dd></div><div><dt>Title</dt><dd>{contact.title ?? '—'}</dd></div><div><dt>Organization</dt><dd>{contact.corporation_name ?? '—'}</dd></div><div><dt>Business address</dt><dd>{contact.business_address ?? '—'}</dd></div></dl></article>)}</div>}<p className="microcopy">Public HPD registration data, joined by exact BBL and exact registration ID. Contact roles describe the HPD filing and are commercial research context only; they do not affect TowerSignal scoring or establish who is responsible for cooling-tower service procurement.</p></>}</section>
      <section><h3>DOB NOW project activity</h3>{!detail.dob_activity_history?.length ? <div className="empty-inline">No exact BBL match was returned from DOB NOW Job Application Filings for this system.</div> : <><p>{detail.dob_activity_history.length.toLocaleString()} exact-BBL job filing{detail.dob_activity_history.length === 1 ? '' : 's'} · {(row.dob_recent_activity_count ?? 0).toLocaleString()} with published lifecycle activity in the last 365 days · {(row.dob_explicit_cooling_tower_count ?? 0).toLocaleString()} explicit cooling-tower description match{row.dob_explicit_cooling_tower_count === 1 ? '' : 'es'}.</p>{detail.dob_activity_history.map((job,index) => <details key={`${job.job_filing_number ?? 'dob-job'}-${index}`} open={index===0}><summary><span>{job.activity_date ? formatDate(job.activity_date) : 'Date not published'} · {job.job_filing_number ?? 'DOB filing'}</span><strong>{dobRelevanceLabel(job.commercial_relevance)}</strong></summary><div className="violation-detail"><p>{job.job_description ?? 'No DOB job description published.'}</p><dl className="identity-grid"><div><dt>Job type</dt><dd>{job.job_type ?? '—'}</dd></div><div><dt>Filing status</dt><dd>{job.filing_status ?? '—'}</dd></div><div><dt>Initial cost</dt><dd>{money(job.initial_cost)}</dd></div><div><dt>Filing date</dt><dd>{job.filing_date ? formatDate(job.filing_date) : '—'}</dd></div><div><dt>Current status date</dt><dd>{job.current_status_date ? formatDate(job.current_status_date) : '—'}</dd></div><div><dt>First permit date</dt><dd>{job.first_permit_date ? formatDate(job.first_permit_date) : '—'}</dd></div><div><dt>Approved date</dt><dd>{job.approved_date ? formatDate(job.approved_date) : '—'}</dd></div><div><dt>Signoff date</dt><dd>{job.signoff_date ? formatDate(job.signoff_date) : '—'}</dd></div><div><dt>Mechanical systems flag</dt><dd>{job.mechanical_systems ? 'Yes' : 'No'}</dd></div><div><dt>Boiler equipment flag</dt><dd>{job.boiler_equipment ? 'Yes' : 'No'}</dd></div><div><dt>DOB owner business</dt><dd>{job.owner_business_name ?? '—'}</dd></div><div><dt>Applicant business</dt><dd>{job.applicant_business_name ?? '—'}</dd></div></dl></div></details>)}<p className="microcopy">DOB NOW job filings are joined by exact BBL. “Cooling tower mention” is used only when the published DOB job description explicitly names cooling-tower work; “Mechanical / boiler” comes only from DOB work-type flags. Other filings remain property-project context. This source does not affect TowerSignal's priority score and does not establish cooling-tower compliance, service responsibility, or a vendor relationship.</p></>}</section>
      <AcrisActivitySection row={row} detail={detail} metadata={metadata} />
      <section><h3>Current TowerSignal signals</h3>{detail.signals.length === 0 ? <div className="empty-inline">No current priority signal was generated.</div> : <div className="signal-list">{detail.signals.map(signal => <article key={signal.type} className={`signal-card signal-card-${signal.evidence_confidence.toLowerCase()}`}><div className="signal-card-head"><strong>{signal.title}</strong><StatusBadge value={signal.evidence_confidence} /></div><div className="fact-class">{signal.fact_class.replaceAll('_',' ')}</div>{signal.date && <div className="signal-date">{formatDate(signal.date)}</div>}<p>{signal.reason}</p></article>)}</div>}</section>
      <section><h3>Historical profile</h3>{!detail.historical_profile ? <div className="empty-inline">Historical profile is not available in this generated record.</div> : <><dl className="identity-grid"><div><dt>Registered</dt><dd>{detail.historical_profile.registration_date ? formatDate(detail.historical_profile.registration_date) : '—'}</dd></div><div><dt>Registration age</dt><dd>{daysAsYears(detail.historical_profile.registration_age_days)}</dd></div><div><dt>First public evidence</dt><dd>{detail.historical_profile.first_public_evidence_date ? formatDate(detail.historical_profile.first_public_evidence_date) : '—'}</dd></div><div><dt>Reported samples</dt><dd>{detail.historical_profile.sample.reported_sample_count.toLocaleString()}</dd></div><div><dt>Sample history range</dt><dd>{detail.historical_profile.sample.first_reported_date ? `${formatDate(detail.historical_profile.sample.first_reported_date)} → ${formatDate(detail.historical_profile.sample.latest_reported_date)}` : '—'}</dd></div><div><dt>Average reported interval</dt><dd>{detail.historical_profile.sample.average_interval_days == null ? '—' : `${detail.historical_profile.sample.average_interval_days} days`}</dd></div><div><dt>Longest reported interval</dt><dd>{detail.historical_profile.sample.longest_interval_days == null ? '—' : `${detail.historical_profile.sample.longest_interval_days} days`}</dd></div><div><dt>NYC Health inspections</dt><dd>{detail.historical_profile.inspection.inspection_count.toLocaleString()}</dd></div><div><dt>Inspections with violations</dt><dd>{detail.historical_profile.inspection.inspections_with_violations.toLocaleString()}</dd></div><div><dt>Violation citations</dt><dd>{detail.historical_profile.inspection.violation_citation_count.toLocaleString()}</dd></div><div><dt>Inspection history range</dt><dd>{detail.historical_profile.inspection.first_inspection_date ? `${formatDate(detail.historical_profile.inspection.first_inspection_date)} → ${formatDate(detail.historical_profile.inspection.latest_inspection_date)}` : '—'}</dd></div><div><dt>Latest cited violation</dt><dd>{detail.historical_profile.inspection.latest_violation_date ? formatDate(detail.historical_profile.inspection.latest_violation_date) : '—'}</dd></div><div><dt>OATH penalty imposed</dt><dd>{money(detail.historical_profile.oath.penalty_imposed_total)}</dd></div><div><dt>OATH paid</dt><dd>{money(detail.historical_profile.oath.paid_amount_total)}</dd></div><div><dt>OATH balance due</dt><dd>{money(detail.historical_profile.oath.balance_due_total)}</dd></div></dl><p className="microcopy">Descriptive history derived from the current authoritative NYC registration, reported sample-date, NYC Health inspection and exact-matched OATH records. Historical intervals do not establish continuous tower operation or retroactive noncompliance.</p></>}</section>
      <section><h3>Sample history</h3>{detail.sample_history.dates.length === 0 ? <div className="empty-inline">No usable public sample history is present in this registration record.</div> : <ol className="timeline">{[...detail.sample_history.dates].reverse().map((dateValue,index,dates) => <li key={dateValue}><strong>{formatDate(dateValue)}</strong>{index === 0 && <span className="latest-tag">Latest</span>}{index < dates.length - 1 && <small>{Math.round((new Date(`${dates[index]}T00:00:00`).getTime()-new Date(`${dates[index+1]}T00:00:00`).getTime())/86400000)} days since prior reported sample</small>}</li>)}</ol>}{detail.sample_history.malformed_values.length > 0 && <p className="warning-note">Unparseable public value(s) retained for provenance: {detail.sample_history.malformed_values.join(', ')}</p>}</section>
      <section><h3>NYC Health inspection history</h3>{detail.inspection_history.length === 0 ? <div className="empty-inline">No published NYC Health inspection history was joined to this system.</div> : detail.inspection_history.map((inspection,index) => <details key={`${inspection.inspection_date}-${inspection.inspection_type}-${index}`} open={index===0}><summary><span>{formatDate(inspection.inspection_date)} · {inspection.inspection_type}</span><strong>{inspection.violation_count} violation{inspection.violation_count === 1 ? '' : 's'}</strong></summary>{inspection.violation_count === 0 ? <p className="inspection-clear">Published row contains no violation/citation values.</p> : inspection.violations.map((violation,vIndex) => <div className="violation-detail" key={`${violation.summons_number}-${vIndex}`}><div><strong>{violation.violation_type ?? 'Violation'}</strong> · {violation.violation_code ?? 'No code'}</div><p>{violation.violation_text ?? violation.citation_text ?? 'No description published.'}</p><small>{violation.law_section ?? 'No law section'}{violation.summons_number ? ` · Summons ${violation.summons_number}` : ''}</small></div>)}</details>)}</section>
      <section><h3>OATH case lifecycle</h3>{!detail.oath_case_history?.length ? <div className="empty-inline">No OATH case was exact-matched to this system's published NYC Health summons numbers.</div> : <>{detail.oath_case_history.map((oathCase,index) => <details key={oathCase.ticket_number} open={index===0}><summary><span>Ticket {oathCase.ticket_number}{oathCase.violation_date ? ` · ${formatDate(oathCase.violation_date)}` : ''}</span><strong>{oathCase.hearing_status ?? 'Status not published'}</strong></summary><div className="violation-detail"><p>{oathCase.violation_description ?? oathCase.charges[0]?.description ?? 'No OATH violation description published.'}</p><dl className="identity-grid"><div><dt>Hearing result</dt><dd>{oathCase.hearing_result ?? '—'}</dd></div><div><dt>OATH compliance status</dt><dd>{oathCase.compliance_status ?? '—'}</dd></div><div><dt>Hearing date</dt><dd>{oathCase.hearing_date ? formatDate(oathCase.hearing_date) : '—'}</dd></div><div><dt>Decision date</dt><dd>{oathCase.decision_date ? formatDate(oathCase.decision_date) : '—'}</dd></div><div><dt>Penalty imposed</dt><dd>{money(oathCase.penalty_imposed)}</dd></div><div><dt>Paid</dt><dd>{money(oathCase.paid_amount)}</dd></div><div><dt>Balance due</dt><dd>{money(oathCase.balance_due)}</dd></div><div><dt>Issuing agency</dt><dd>{oathCase.issuing_agency ?? '—'}</dd></div></dl>{oathCase.charges.length > 0 && <ul className="score-list">{oathCase.charges.map((charge,chargeIndex) => <li key={`${charge.code}-${chargeIndex}`}><strong>{charge.code ?? 'Charge'}</strong><span>{charge.code_section ? `${charge.code_section} · ` : ''}{charge.description ?? 'No charge description'}{charge.infraction_amount != null ? ` · ${money(charge.infraction_amount)}` : ''}</span></li>)}</ul>}<p className="microcopy">Matched by exact NYC Health summons number to OATH ticket number. OATH-published case status and outcome are source facts and remain separate from TowerSignal's priority score.</p></div></details>)}</>}</section>
      <section><h3>TowerSignal History</h3>{historyEvents.length === 0 ? <div className="empty-inline">No changes have been observed for this system since TowerSignal history collection began {formatTimestamp(historyStartedAt)}.</div> : <ol className="timeline history-timeline">{historyEvents.map((event,index) => <li key={`${event.detected_at}-${event.event_type}-${index}`}><strong>{formatTimestamp(event.detected_at)}</strong><span>{historyLabel(event.event_type)}</span>{event.source_observation_date && <small>Source observation {formatDate(event.source_observation_date)}</small>}<small>{compactHistoryValue(event.previous_value)} → {compactHistoryValue(event.new_value)}</small><small>{event.source} · {event.evidence_basis}</small></li>)}</ol>}<p className="microcopy">Detection time means TowerSignal first observed a difference between preserved snapshots. It is not necessarily the date the underlying real-world event occurred.</p></section>
      <section><h3>Why this score</h3>{detail.scoring.components.length ? <ul className="score-list">{detail.scoring.components.map((component,index) => <li key={`${component.reason}-${index}`}><strong>+{component.points}</strong><span>{component.reason}</span></li>)}</ul> : <div className="empty-inline">No priority points were assigned.</div>}<p className="microcopy">Commercial research-priority score only. Not a health-risk, safety, or compliance score. Model {detail.scoring.priority_model_version}.</p></section>
      <section><h3>Source & provenance</h3><p>Generated {formatTimestamp(detail.metadata.generated_at)} · Rules {detail.metadata.rules_version} · Priority model {detail.metadata.priority_model_version}</p>{detail.metadata.oath_match_basis && <p className="microcopy">OATH lifecycle join: exact summons/ticket identity only · {detail.metadata.oath_matched_ticket_count?.toLocaleString() ?? 0} matched of {detail.metadata.oath_requested_ticket_count?.toLocaleString() ?? 0} cooling-tower summons numbers.</p>}{detail.metadata.pluto_requested_bbl_count != null && <p className="microcopy">PLUTO building join: exact BBL only · {detail.metadata.pluto_matched_bbl_count?.toLocaleString() ?? 0} matched of {detail.metadata.pluto_requested_bbl_count.toLocaleString()} usable cooling-tower BBLs.</p>}{detail.metadata.dob_requested_bbl_count != null && <p className="microcopy">DOB NOW job join: exact BBL only · {detail.metadata.dob_matched_bbl_count?.toLocaleString() ?? 0} matched of {detail.metadata.dob_requested_bbl_count.toLocaleString()} usable cooling-tower BBLs · {detail.metadata.dob_matched_filing_count?.toLocaleString() ?? 0} job filings · {detail.metadata.dob_explicit_cooling_tower_filing_count?.toLocaleString() ?? 0} descriptions explicitly naming cooling-tower work.</p>}{detail.metadata.hpd_requested_bbl_count != null && <p className="microcopy">HPD contact join: exact BBL to registration, then exact registration ID to contacts · {detail.metadata.hpd_matched_registration_bbl_count?.toLocaleString() ?? 0} registration matches and {detail.metadata.hpd_matched_contact_bbl_count?.toLocaleString() ?? 0} BBLs with contacts from {detail.metadata.hpd_requested_bbl_count.toLocaleString()} usable cooling-tower BBLs.</p>}{detail.metadata.planimetric_requested_bin_count != null && <p className="microcopy">Planimetric physical-location join: exact BIN only · {detail.metadata.planimetric_matched_bin_count?.toLocaleString() ?? 0} matched of {detail.metadata.planimetric_requested_bin_count.toLocaleString()} usable cooling-tower BINs · {detail.metadata.planimetric_matched_feature_count?.toLocaleString() ?? 0} unique mapped physical features from {detail.metadata.planimetric_imagery_year ?? 2022} imagery.</p>}{detail.metadata.sources.map(source => <div className="source-row" key={source.dataset_id}><strong>{source.name}</strong><span>{source.dataset_id} · {source.source_record_count.toLocaleString()} source rows{source.matched_record_count != null ? ` · ${source.matched_record_count.toLocaleString()} exact-matched records` : ''}</span><small>Retrieved {formatTimestamp(source.retrieved_at)}{source.source_last_updated_at ? ` · Source last updated ${formatTimestamp(source.source_last_updated_at)}` : ''}{source.source_query_scope ? ` · ${source.source_query_scope}` : ''}</small></div>)}</section>
    </>}
  </aside>
}
