import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {chromium} from 'playwright';
const BASE='https://jeremyhennessy.github.io/TowerSignal/',OUT='desktop-demo-supplement';for(const d of ['screens','states','assets'])fs.mkdirSync(`${OUT}/${d}`,{recursive:true});
const manifest={started_at:new Date().toISOString(),base:BASE,viewport:{width:1600,height:1000},device_scale_factor:2,capture_commit:process.env.GITHUB_SHA,shots:[],errors:[],network_failures:[],demonstration:null};const hash=b=>crypto.createHash('sha256').update(b).digest('hex');const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,60);const write=(n,o)=>fs.writeFileSync(`${OUT}/${n}`,JSON.stringify(o,null,2));
const browser=await chromium.launch(),context=await browser.newContext({viewport:manifest.viewport,deviceScaleFactor:2}),page=await context.newPage();page.setDefaultTimeout(14000);let apiRoot='',authHeaders={};const demoIds=['2000012577','2000000855','2000015564'];let demoTouched=false;const records={};
page.on('request',r=>{if(r.url().includes('/rest/v1/workflow_')){apiRoot=r.url().split('/rest/v1/')[0]+'/rest/v1/';const h=r.headers();for(const k of ['authorization','apikey'])if(h[k])authHeaders[k]=h[k];}});
page.on('response',r=>{if(r.status()>=400)manifest.network_failures.push({url:r.url().split('?')[0],status:r.status()});if(r.url().includes('/rest/v1/workflow_')&&r.request().method()==='GET'&&r.ok())r.json().then(j=>records[r.url().split('/rest/v1/')[1].split('?')[0]]=j).catch(()=>{});});page.on('pageerror',e=>manifest.errors.push({type:'pageerror',message:String(e)}));
async function settle(ms=1600){await page.waitForTimeout(ms);await page.locator('.loading-page').waitFor({state:'hidden',timeout:90000}).catch(()=>{});await page.evaluate(()=>document.fonts.ready);}
async function go(route){await page.goto(BASE+route,{waitUntil:'domcontentloaded',timeout:100000});await settle(2400);}
async function snap(name,selector=null,maxHeight=3800){try{await settle(750);let clip;const target=selector?typeof selector==='string'?page.locator(selector).first():selector:null;if(target){await target.waitFor({state:'visible'});await target.scrollIntoViewIfNeeded();await page.waitForTimeout(450);const b=await target.boundingBox(),scroll=await page.evaluate(()=>({x:scrollX,y:scrollY}));clip={x:Math.max(0,b.x+scroll.x),y:Math.max(0,b.y+scroll.y),width:Math.min(1600,b.width),height:Math.min(maxHeight,b.height)};}else{await page.evaluate(()=>scrollTo(0,0));clip={x:0,y:0,width:1600,height:Math.min(maxHeight,await page.evaluate(()=>document.documentElement.scrollHeight))};}const f=`screens/${name}.png`;await page.screenshot({path:`${OUT}/${f}`,clip,animations:'disabled',timeout:45000});const state=await page.evaluate(()=>({url:location.href,title:document.title,text:document.body.innerText,buttons:[...document.querySelectorAll('button')].filter(e=>e.getBoundingClientRect().width>0).map(e=>({text:e.innerText,label:e.getAttribute('aria-label'),cls:e.className})),elements:[...document.querySelectorAll('h1,h2,h3,h4,section,article,table,nav,details,[class*=metrics],[class*=summary],[class*=inspector]')].filter(e=>e.getBoundingClientRect().width>0).map(e=>{const b=e.getBoundingClientRect();return {tag:e.tagName,id:e.id,cls:e.className,text:e.innerText?.slice(0,200),box:{x:b.x+scrollX,y:b.y+scrollY,width:b.width,height:b.height}}}),scripts:[...document.querySelectorAll('script[src]')].map(e=>e.src)}));write(`states/${name}.json`,state);manifest.shots.push({name,file:f,url:page.url(),clip,captured_at:new Date().toISOString(),sha256:hash(fs.readFileSync(`${OUT}/${f}`)),demonstration:demoTouched});console.log('CAPTURE',name);}catch(e){manifest.errors.push({shot:name,error:String(e)});}}
async function clickCapture(route,label,name){try{await go(route);await page.getByRole('button',{name:label,exact:true}).first().click();await settle();await snap(name);await snap(name+'-viewport',null,1000);}catch(e){manifest.errors.push({state:name,error:String(e)});}}
async function getOwn(table){const r=await context.request.get(apiRoot+table+'?select=*',{headers:authHeaders});if(!r.ok())throw Error(`Own workflow read failed ${r.status()}`);return r.json();}
async function cleanup(){if(!demoTouched)return;const cleanup=[];for(const table of ['workflow_watchlist_members','workflow_accounts'])for(const id of demoIds){const r=await context.request.delete(`${apiRoot}${table}?system_id=eq.${id}`,{headers:authHeaders});cleanup.push({table,id,status:r.status()});}const a=await getOwn('workflow_accounts'),m=await getOwn('workflow_watchlist_members');manifest.demonstration.cleanup={operations:cleanup,accounts_after:a.length,memberships_after:m.length,restored:a.length===0&&m.length===0};if(a.length||m.length)throw Error('Demonstration cleanup did not restore empty test profile');demoTouched=false;}
try{
await go('#/home');if(await page.getByLabel('Email',{exact:true}).count()){const password=fs.readFileSync('tests/e2e/auth.helpers.ts','utf8').match(/const PASSWORD = '([^']+)'/)[1];await page.waitForTimeout(11000);await page.getByLabel('Email',{exact:true}).fill('towersignal-e2e-34636977078-1-desktop@example.com');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Sign in to TowerSignal',exact:true}).waitFor({state:'hidden',timeout:30000});await settle();}
for(const label of ['All updates','Linked buildings','Reference library'])await clickCapture('#/home',label,'20-home-'+slug(label));
try{await go('#/home');await page.locator('.li-match-button').first().click();await snap('20-home-linked-building-drilldown',null,3000);}catch(e){manifest.errors.push({state:'home-drilldown',error:String(e)});}
for(const label of ['High priority','New violations','OATH activity','DOB / permits','Sampling','Property / contact'])await clickCapture('#/monitor',label,'21-monitor-'+slug(label));
for(const label of ['New equipment','Compliance','Tower status','Sampling','Operation'])await clickCapture('#/nys-changes',label,'22-nys-changes-'+slug(label));
for(const label of ['NYC Distribution','NYS Public Water','Lead Service Lines'])await clickCapture('#/water-quality',label,'23-water-'+slug(label));await clickCapture('#/water-quality','Samples','23-water-distribution-samples');
for(const id of demoIds){for(const mode of ['Summary','Sales','Field','Evidence','History']){try{await go('#/account/'+id);await page.getByRole('button',{name:new RegExp('^'+mode+'\\s')}).first().click();await settle();await snap('24-'+id+'-'+mode.toLowerCase());await snap('24-'+id+'-'+mode.toLowerCase()+'-viewport',null,1000);for(const [sel,suffix,height] of mode==='Sales'?[['.sales-pack-metrics','metrics',1100],['.sales-pack-objective','objective',500],['.sales-pack-panel','before-call',1800]]:mode==='Field'?[['.technician-field-pack','field-pack',1700],['.planimetric-section','roof',1800],['.planimetric-map-shell','roof-map',1000],['.domestic-water-section','domestic-water',2000]]:mode==='Evidence'?[['.property-enforcement-section','enforcement',2200]]:[]){if(await page.locator(sel).isVisible().catch(()=>false))await snap('24-'+id+'-'+suffix,sel,height);}if(mode==='Sales'){const d=page.locator('.sales-known-firms');if(await d.count()){if(await d.getAttribute('open')===null)await d.locator('summary').click();await snap('24-'+id+'-observed-firms',d,1600);}}}catch(e){manifest.errors.push({account:id,mode,error:String(e)});}}}
await go('#/portfolios');await page.locator('.portfolio-group-button').filter({hasText:'NEW YORK UNIVERSITY'}).first().click();await snap('25-portfolio-nyu');if(await page.locator('.portfolio-detail').isVisible())await snap('25-portfolio-nyu-detail','.portfolio-detail',2800);
await go('#/nys-account/NYS-4');await snap('26-nys-account-hawthorne');
for(const [id,name] of [['observed-company-9a049993a3ba62961d8f','metro'],['observed-company-a3bc0790172dfd16ed5a','rmc']]){await go('#/company/'+id);await snap('27-firm-'+name);for(const [sel,suf] of [['.known-firm-profile-metrics','metrics'],['.firm-site-map-grid','map'],['.company-evidence-card','commercial']])if(await page.locator(sel).first().isVisible().catch(()=>false))await snap('27-firm-'+name+'-'+suf,sel,1500);if(name==='metro'){const row=page.locator('.firm-prospect-sites-table tbody tr').filter({hasText:/515 east 72nd/i}).first();if(await row.count()){await row.click();await settle(2200);await snap('27-metro-selected-site','.firm-site-map-grid',1800);}}}
await go('#/opportunities');const svc=page.getByLabel('Procurement service category');if(await svc.count()){const opts=await svc.locator('option').evaluateAll(es=>es.map(e=>({value:e.value,text:e.textContent})));const v=opts.find(o=>/cooling tower/i.test(o.text));if(v)await svc.selectOption(v.value);await snap('28-procurement-cooling-tower');}
await go('#/source-health');await snap('29-source-health-complete',null,6000);const details=page.locator('details');for(let i=0;i<await details.count()&&i<8;i++){const d=details.nth(i);if(await d.getAttribute('open')===null)await d.locator('summary').first().click();await snap('29-source-health-detail-'+i,d,2400);}
// Bounded demo in existing empty E2E verification profile, never the user's private account.
await go('#/workflow');await settle(2500);if(apiRoot&&authHeaders.authorization){const beforeA=await getOwn('workflow_accounts'),beforeM=await getOwn('workflow_watchlist_members');manifest.demonstration={profile:'Existing E2E Verification account',purpose:'Native demonstration watchlist over three real public accounts; not customer activity, sales results or user private workflow',baseline_accounts:beforeA.length,baseline_memberships:beforeM.length,system_ids:demoIds};if(beforeA.length===0&&beforeM.length===0){demoTouched=true;for(const id of demoIds){await go('#/account/'+id);const section=page.locator('.workflow-account-section').first();await section.locator('select').first().selectOption('monitor');const box=section.getByRole('checkbox').first();if(await box.count())await box.check();await section.getByRole('button',{name:'Save workflow state',exact:true}).click();await settle(1800);}await go('#/workflow');await snap('30-demo-workflow-overview',null,2500);const row=page.locator('.workflow-command-table tbody tr').filter({hasText:'1813 Oriental'}).first();if(await row.count())await row.click();await settle(1600);await snap('30-demo-workflow-selected',null,2400);await snap('30-demo-workflow-inspector','.workflow-account-inspector',1500);for(const label of ['Table','Map','Map + table']){await page.locator('.workflow-account-view-toggle').getByRole('button',{name:label,exact:true}).click();await snap('30-demo-workflow-'+slug(label),null,2600);}for(const label of ['Changes','Actions']){await page.getByRole('tab',{name:new RegExp('^'+label)}).click();await snap('30-demo-workflow-'+slug(label),null,2200);}await cleanup();await go('#/workflow');await snap('30-demo-cleanup-restored',null,1400);}else manifest.demonstration.skipped='Test profile was not empty; no private records changed';}else manifest.demonstration={skipped:'No existing authenticated workflow API context was available; no data changed'};
for(const [url,name] of [[BASE+'marketing/towersignal-logo.webp','towersignal-logo.webp'],[BASE+'marketing/towersignal-hero.webp','towersignal-hero.webp'],['https://upload.wikimedia.org/wikipedia/commons/7/7b/June2019ManhattanPanoramaFromHoboken.jpg','daylight-manhattan-DavFace-CCBYSA4.jpg']]){try{const r=await context.request.get(url,{timeout:90000});if(r.ok()){const b=await r.body();fs.writeFileSync(`${OUT}/assets/${name}`,b);manifest[name]={url,bytes:b.length,sha256:hash(b)};}else manifest.errors.push({asset:name,status:r.status()});}catch(e){manifest.errors.push({asset:name,error:String(e)});}}
}catch(e){manifest.errors.push({fatal:String(e)});process.exitCode=1;}
finally{try{await cleanup();}catch(e){manifest.errors.push({cleanup_failure:String(e)});process.exitCode=1;}manifest.finished_at=new Date().toISOString();write('manifest.json',manifest);await browser.close();console.log(JSON.stringify({shots:manifest.shots.length,errors:manifest.errors,demonstration:manifest.demonstration}));}
