import React from 'react'
import ReactDOM from 'react-dom/client'
import { AuthGate } from './auth/AuthGate'
import './styles/app.css'
import './styles/history.css'
import './styles/nys.css'
import './styles/redesign.css'
import './styles/redesign-fixes.css'
import './styles/acris.css'
import './styles/workflow.css'
import './styles/product-redesign.css'
import './styles/product-redesign-fixes.css'
import './styles/product-redesign-final.css'
import './styles/auth-gate.css'
import './styles/toronto.css'

ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AuthGate /></React.StrictMode>)
